[tox]
envlist = py36,py37,py38,py39,py310,py311,py312,py313,py314

[testenv]
# install pytest in the virtualenv where commands will be executed
deps =
    pytest
    setuptools
commands =
    pytest -vvs

    